### PR TITLE
#163368795 Refactoring landing page 

### PR DESCRIPTION
**Pull request by Oluwaseyi000**
#### What does this PR do?
This PR refactor the landing page.
It decouple the landing page, user sign in page, user login in page and admin login page
It improve the general look and feel of the landing page

#### Description of Task to be completed?

- [ ] The landing page was refactor and redisigned

- [ ] User login page was moved to a separate page

- [ ] User signup page was moved to a separate page

- [ ] Admin login page was moved to a separate page

#### How should this be manually tested?
After successful code review and merge by LFA, this link: https://oluwaseyi000.github.io/Questioner_Andela/ can be visited to view the PR changes

#### What are the relevant pivotal tracker stories?
[163368795](https://www.pivotaltracker.com/story/show/163368795)

### CODE REVIEW

**Comment by JCanaks** [comment]
@Oluwaseyi000 Please follow the format for commit messages as specified

**Comment by JCanaks** [comment]
@Oluwaseyi000 Your PR Description says you refactored the landing page but the description includes login pages and the user signup page. Pls raise PRs that handles one specific feature or similar features at a time moving forward

**Comment by JCanaks** [comment]
Please follow the convention for branch naming as specified

**Comment by JCanaks** [comment]
Nice job so far. Here are some feedback you need to work on:
- On the home page you underlined `Welcome to Questioner`. Pls remove that.
- Since you don't have much information on your landing page pls make everything (Header, Body, Footer) visible on the screen without the user having to scroll only to see the header.
- In the login page centralize your login form let it be at the center of the body section
- In the signup and login page. Remove the `Fields with * are required` from the top of the form to the bottom of the form (i.e underneath the last text field) and centralize the `User Login` and `User Signup` in the login and signup page respectively 
- Remove the `Welcome guest` from the authentication pages (login and signup) since the user has actually not accessed the app its not needed. Pls add a link to the home page in that position instead and a link to either the sign in or login page depending on the page the user is on
- Also let the questioner logo in the signup and login page link to the homepage

**Comment by Oluwaseyi000** [comment]
> @Oluwaseyi000 Please follow the format for commit messages as specified



> Nice job so far. Here are some feedback you need to work on:
> 
> * On the home page you underlined `Welcome to Questioner`. Pls remove that.
> * Since you don't have much information on your landing page pls make everything (Header, Body, Footer) visible on the screen without the user having to scroll only to see the header.
> * In the login page centralize your login form let it be at the center of the body section
> * In the signup and login page. Remove the `Fields with * are required` from the top of the form to the bottom of the form (i.e underneath the last text field) and centralize the `User Login` and `User Signup` in the login and signup page respectively
> * Remove the `Welcome guest` from the authentication pages (login and signup) since the user has actually not accessed the app its not needed. Pls add a link to the home page in that position instead and a link to either the sign in or login page depending on the page the user is on
> * Also let the questioner logo in the signup and login page link to the homepage

I have made the recommended changes.

Thanks for the feedback

**Comment by JCanaks** [comment]
Nice work on the homepage, just a few feedback:
- Centralize your `User Signin` and `User Signup` header
- Increase the height of your signin from a little as it is quite small
- add a little spacing between your `User Signin` and `User Signup` header and the form
- Why did you remove the `Fields with * are required` message? I just requested that you put it below the last form field.

**Pull request merged**
